version: '3.8'

services:
  db:
    image: postgres:17
    container_name: maison_jungle_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: maison_jungle
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: maison_jungle_backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/maison_jungle
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: maison_jungle_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: